name: Node.js CI

on:
  push:
    branches:
     - main
     - Oshayer

  pull_request:
    branches:
     - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # You can specify your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Start the server
      run: npm start &

    - name: Wait for the server to start
      run: sleep 5  # Adjust the sleep duration as needed

    - name: Run tests
      run: curl http://localhost:3000 
      
     # Adjust the URL if you chose a different port
    - name: Merge branches into main
      run: | 
        git checkout main
        git pull -u origin main
        git merge Oshayer
        git push -u origin main

    - name: Stop the server
      run: pkill -f "node app.js"  # Adjust the script name if necessary
